### ISSUE TITLE
Plugin is broken for starting zoom meetings as a host

### ISSUE THREAD

**Issue by Yannik** [EdoardoTosin/ZooMeeting-Redirector#2]
**Describe the bug**

**To Reproduce**
1. Create a zoom meeting as meeting host, and start it 
2. A page not found error is shown

**Expected behavior**
Zoom meeting should start

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Version 108

**Additional context**

The reason for this most likely is that the plugin redirects to e.g. `https://us04web.zoom.us/wc/start/72064777461`.
However, the correct URL seems to be `https://us04web.zoom.us/wc/72064777461/start`

**Comment by EdoardoTosin** [comment]
Thank you for opening the issue. I already fixed it and released a new version.
Happy Holidays! 🎄

**Comment by Yannik** [comment]
Thank you for the quick response, it is working now!

Happy holidays to you as well :-)
